package com.esphere.iceberg.payloads;

public enum EventType {

	GET_REPO_META_DATA,GET_META_DATA,GET_DATA, PUT_DATA, WRITE_REPLICA, MASTER_ELECTION, LEADER_ELECTION, NODE_JOIN, NODE_LEFT, HEART_BEAT,
	MASTER_LIST_UPDATE , HASH_ALLOCATION, PING, HASH_ALLOCATED, OK;

}
